const data ={
    products:[
        {
            name: 'Nike slim shirt',
            slug: 'nike-slim-shirt',
            category:'Shirts',
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: '4.5',
            numReviews: 10,
            description: 'High quality product',
        },
        {
            name: 'Nike slim shirt',
            slug: 'nike-slim-shirt',
            category:'Shirts',
            image: '/images/p2.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: '4.5',
            numReviews: 10,
            description: 'High quality product',
        },
        {
            name: 'Adidas fit shirt',
            slug: 'adidas-fit-shirt',
            category:'Shirts',
            image: '/images/p3.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Adidad',
            rating: '4.0',
            numReviews: 10,
            description: 'High quality product',
        },
        {
            name: 'Nike slim pant',
            slug: 'nike-slim-pant',
            category:'Pants',
            image: '/images/p4.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: '4.5',
            numReviews: 10,
            description: 'High quality product',
        },
    ],
};

export default data;