const data ={
    products:[
        {
            name: 'Nike slim shirt',
            slug: 'nike-slim-shirt',
            category:'Shirts',
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: '4.5',
            numReviews: 10,
            decription: 'High quality product',
        },
        {
            name: 'Nike slim shirt',
            slug: 'nike-slim-shirt',
            category:'Shirts',
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: '4.5',
            numReviews: 10,
            decription: 'High quality product',
        },
        {
            name: 'Adidad fit shirt',
            slug: 'adidad-fit-shirt',
            category:'Shirts',
            image: '/images/p2.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Adidad',
            rating: '4.5',
            numReviews: 10,
            decription: 'High quality product',
        },
        {
            name: 'Nike slim pant',
            slug: 'nike-slim-pant',
            category:'Pants',
            image: '/images/p3.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: '4.5',
            numReviews: 10,
            decription: 'High quality product',
        },
        {
            name: 'Adidad fit pant',
            slug: 'adidad-fit-pant',
            category:'Shirts',
            image: '/images/p2.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Adidad',
            rating: '4.5',
            numReviews: 10,
            decription: 'High quality product',
        },
    ],
};